daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
  - enhancement
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
closeComment: >
  This issue has been automatically closed due to inactivity.
# Complete refresh Sun Nov  9 12:26:27 CET 2025
# Auto-updated 20251109_123235
# Updated Sun Nov  9 12:50:13 CET 2025
# Updated Sun Nov  9 12:52:13 CET 2025
# Updated Sun Nov  9 12:56:48 CET 2025
