name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'development' }}
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/configure-pages@v4
      
      - name: Build site
        run: |
          set -e
          mkdir -p _site/assets
          
          # Create main page from template
          envsubst < .github/templates/index.html.template > _site/index.html
          
          # Copy documentation
          cp -r docs/* _site/ 2>/dev/null || true
          
          # Generate API documentation
          echo "Generating documentation..." > _site/build.log
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'development' }}
          REPOSITORY: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          BUILD_TIME: ${{ github.run_number }}
      
      - uses: actions/upload-pages-artifact@v4
        with:
          path: _site
      
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
