name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        - production

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'development' }}
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/configure-pages@v4
      
      - name: Build site
        run: |
          mkdir -p _site
          cat > _site/index.html << 'EOF'
<!DOCTYPE html>
<html><head><title>VMware PowerCLI All</title></head>
<body><h1>VMware PowerCLI All</h1><p>Deployment successful</p></body></html>
EOF
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'development' }}
          REPOSITORY: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
          BUILD_TIME: ${{ github.run_number }}
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
