name: PowerShell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test PowerShell Script
      shell: pwsh
      run: |
        Write-Host "Testing PowerShell script..."
        if (Test-Path "./Install-PowerCLI-All.ps1") {
          Write-Host "Main script exists"
        } else {
          Write-Error "Main script not found"
          exit 1
        }
        Write-Host "PowerShell test completed successfully!"