name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run basic security check
        run: |
          echo "Running basic security checks..."
          # Check for common secrets patterns
          if grep -r "password.*=" . --exclude-dir=.git || grep -r "api.*key" . --exclude-dir=.git; then
            echo "Warning: Potential secrets found"
          fi
          echo "Security check completed"
